sonar.projectKey=fragforce_read
sonar.organization=fragforce

sonar.exclusions=**/migrations/**

sonar.javascript.exclusions=**/templates/**

sonar.test.inclusions=**/test_*.py,**/tests.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13

sonar.qualitygate.wait=true
