# Generated by Django 6.0.6 on 2026-06-18 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('illustrator', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('copyright_notice', models.TextField(blank=True)),
                ('permission_phrasing', models.TextField(blank=True)),
                ('public_domain', models.BooleanField(default=False)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('max_narrators', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_duration', models.CharField(blank=True, max_length=50)),
                ('full_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='recordings/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='books.book')),
                ('narrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='books.narrator')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=10)),
                ('label_text', models.CharField(max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='books.book')),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='books.recording')),
            ],
            options={
                'verbose_name': 'QR code',
                'verbose_name_plural': 'QR codes',
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attested_at', models.DateTimeField(auto_now_add=True)),
                ('attestation_text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='books.book')),
                ('narrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='books.narrator')),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='books.recording')),
            ],
        ),
    ]
