# Generated by Django 6.0.6 on 2026-06-18 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_narrator_passphrase'),
        ('registration', '0002_alter_invitelink_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrator',
            name='registered_via_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narrators', to='registration.eventcode'),
        ),
    ]
