# Generated by Django 6.0.6 on 2026-06-23 17:05

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_narrator_registered_via_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(upload_to=books.models.recording_upload_path),
        ),
    ]
