# Generated by Django 6.0.6 on 2026-06-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_recording_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='flagged_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
