# Generated by Django 6.0.6 on 2026-06-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_recording_flag_reason_recording_flagged_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12),
        ),
    ]
