# Generated by Django 6.0.6 on 2026-06-29 15:20

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_qrcode_password_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='password',
            field=models.CharField(default=books.models.generate_qr_password, max_length=30),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='short_code',
            field=models.CharField(default=books.models.generate_qr_short_code, max_length=8, unique=True),
        ),
    ]
