# Generated by Django 6.0.6 on 2026-06-18 16:10

import django.db.models.deletion
import registration.wordlist
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_narrator_passphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(help_text="Internal label, e.g. 'October 2026 VTO Event'", max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=registration.wordlist.generate_passphrase, max_length=200, unique=True)),
                ('label', models.CharField(help_text="Who this invite is for, e.g. 'Jordan - Fragforce Discord'", max_length=255)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('narrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_link', to='books.narrator')),
            ],
        ),
    ]
