# Generated by Django 6.0.6 on 2026-06-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
